name: fiveguysstore
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  build_runner: ^2.4.15
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  loading_indicator: ^3.1.1

  riverpod_annotation: ^2.6.1
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  shared_preferences: ^2.5.3
  tap_debouncer: ^2.2.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  logger: ^2.5.0

flutter:
  uses-material-design: true
